### ISSUE TITLE
无法连续对话

### ISSUE THREAD

**Issue by beichen123-hub** [dfvips/xunfeixinghuo#2]
代码报错 无法联系对话 
![image](https://github.com/dfvips/xunfeixinghuo/assets/70616669/ded9b61a-f2c0-49a9-84dc-26e5c727a538)

**Comment by dfvips** [comment]
> 代码报错 无法联系对话 ![image](https://user-images.githubusercontent.com/70616669/237902404-ded9b61a-f2c0-49a9-84dc-26e5c727a538.png)

注意右下角，提示"module ‘websocket‘ has no attribute ‘enableTrace‘"的情况，参考https://blog.csdn.net/u014534808/article/details/113655577。建议搭配好websocket和client后，先单独测试text2audio.py，试试能否导出音频，再进行对话。

**Comment by dfvips** [comment]
"module ‘websocket‘ has no attribute ‘enableTrace‘"的提示，意思是websocket和websocket-client搭配不匹配，或者没有安装其中的另一个。
