### ISSUE TITLE
获取不到回复

### ISSUE THREAD

**Issue by heicathei** [dfvips/xunfeixinghuo#4]
![image](https://github.com/dfvips/xunfeixinghuo/assets/94883313/3aa4962c-a5a3-4fb3-9658-c684e342bfe2)

**Comment by heicathei** [comment]
提示请求被拦截
![image](https://github.com/dfvips/xunfeixinghuo/assets/94883313/7d59fab9-c8c3-45fb-8060-98ce4c948fe6)

**Comment by dfvips** [comment]
这个问题，应该是因为Cookie信息过期了，或者你账号已经被系统风控，你可以试试填写新的cookie信息试试，如果还不行，我也不知道怎么解决，我这边测试，是没有问题的。。
<img width="1352" alt="image" src="https://github.com/dfvips/xunfeixinghuo/assets/21048630/935f124b-e99b-4a3c-bf57-1a7c14efe89f">

> 提示请求被拦截 ![image](https://user-images.githubusercontent.com/94883313/239213049-7d59fab9-c8c3-45fb-8060-98ce4c948fe6.png)

**Comment by heicathei** [comment]
离谱，网页是正常的，我发现只要网页问个问题，掉接口就正常了

**Comment by dfvips** [comment]
> 离谱，网页是正常的，我发现只要网页问个问题，掉接口就正常了

目前没看到有什么新的检测技术。可以用就行。

**Comment by supersaiyan2019** [comment]
我也遇到这个问题，有时莫名其妙能恢复，有时重启程序能好，有时好不了

**Comment by supersaiyan2019** [comment]
我对比了一下ChatALL那边的实现，他的fd 和 GtToken 都是动态获取的，不知跟这个有无关系。不排除讯飞最近试验性地增加了设备验证，在页面上问过问题后，暂时放行了，但过一段时间或访问压力过大时又重新检测了，供参考

// Create FormData payload
        const GtToken = await this.getGtToken();
        const formData = new FormData();
        formData.append("fd", String(+new Date()).slice(-6));
        formData.append("chatId", this.chatId);
        formData.append("text", prompt);
        formData.append("GtToken", GtToken);
        formData.append("clientType", "1");

**Comment by supersaiyan2019** [comment]
![2023-05-20_21-15-15](https://github.com/dfvips/xunfeixinghuo/assets/130198547/fc91f95b-6668-4967-a867-e54f7e171418)
我在用fiddler的时候发现在调chat_message/chat之前，讯飞有去调riskct.geetest.com

**Comment by supersaiyan2019** [comment]
弄错了，ChatALL是有个前端，不一样。但请求被拦截就是因为弹出了验证窗口，楼主说的登录进去发信息就表示点掉了验证窗口，但过段时间又来了

**Comment by heicathei** [comment]
不是的，那个验证窗口不是每次都有，偶尔会有，但是只要你用网页版发送了消息，就有半个小时以内调用接口可以正常使用，半个小时之后如果没有使用过网页版，再调用接口还是会继续被拦截，我也没有找到验证的接口

**Comment by Cvandia** [comment]
同样的问题出现

**Comment by doublewinter0** [comment]
可以看看我的项目：https://github.com/doublewinter0/xfyun-xinghuo
