### ISSUE TITLE
有打算接入钉钉机器人吗

### ISSUE THREAD

**Issue by 17337162621254271304** [dfvips/xunfeixinghuo#5]
RT

**Comment by dfvips** [comment]
由于这个不是官方授权的API，所以有一定的不稳定性，如果作为钉钉机器人的话，没办法保证它掉登录的问题。当初开发这个，主要是方便自己的项目接入。

> RT

**Comment by doublewinter0** [comment]
> 

可以看看我的项目：https://github.com/doublewinter0/xfyun-xinghuo
