### ISSUE TITLE
回复中一直包含错误信息[SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by zdevc** [dfvips/xunfeixinghuo#7]
![image](https://github.com/dfvips/xunfeixinghuo/assets/40593221/9418918e-e47e-44dc-b7ca-6333efe5f52a)

**Comment by dfvips** [comment]
这个错误通常出现在Python中使用SSL连接时，无法验证服务器的证书。通常的因为你抓包或者使用其他影响ssl握手的工具，导致python验证异常。你可以在请求的URL的地方，后面加 verify=False。

**Comment by zdevc** [comment]
> 这个错误通常出现在Python中使用SSL连接时，无法验证服务器的证书。通常的因为你抓包或者使用其他影响ssl握手的工具，导致python验证异常。你可以在请求的URL的地方，后面加 verify=False。

![image](https://github.com/dfvips/xunfeixinghuo/assets/40593221/eb0a4d7f-aaa2-4f88-a780-d5af4a3defef)
![image](https://github.com/dfvips/xunfeixinghuo/assets/40593221/a1a63c77-2c7d-4d85-90c1-f552da2aa1c9)
在各处request请求的地方加了 verify=False，出现了更多警告，仍然存在之前的错误信息

**Comment by dfvips** [comment]
这个警告是由Python的requests库发出的，它指示你正在进行一个未经验证的HTTPS请求。建议你添加证书验证以增强安全性。
要解决这个警告，可以通过以下方法来处理：
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
